### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException for non "execute shell" builders

### ISSUE THREAD

**Issue by HerrBerg** [jenkinsci/docker-custom-build-environment-plugin#11]
First of all: Oki-docki works fine when using the "execute shell" builder (and maybe others)

I found this bug when trying to use the "sonarqube runner" but it also occurs when using e.g.:
* "python builder" from shining panda plugin
* "invoke ant"
* "invoke top-level maven targets"

When I configure a simple freestyle project containing one of the above mentioned build-steps (in this case  "python builder") and also enable oki docki I get the following error message:

    Building remotely on docker01 in workspace /root/workspace/test
    Docker container 1a0c2d0aed4409ad5c66892b6ac23eec6670b491e241468ae5b454477f9bd200 started to host the build
    FATAL: 3
    java.lang.ArrayIndexOutOfBoundsException: 3
            at hudson.Launcher.maskedPrintCommandLine(Launcher.java:664)
            at hudson.Launcher$LocalLauncher.launch(Launcher.java:793)
            at hudson.Launcher$ProcStarter.start(Launcher.java:381)
            at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1136)
            at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1101)
            at hudson.remoting.UserRequest.perform(UserRequest.java:121)
            at hudson.remoting.UserRequest.perform(UserRequest.java:49)
            at hudson.remoting.Request$2.run(Request.java:324)
            at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
            at java.util.concurrent.FutureTask.run(FutureTask.java:166)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:701)
            at ......remote call to docker01(Native Method)
            at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1356)
            at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
            at hudson.remoting.Channel.call(Channel.java:752)
            at hudson.Launcher$RemoteLauncher.launch(Launcher.java:916)
            at hudson.Launcher$DecoratedLauncher.launch(Launcher.java:1026)
            at com.cloudbees.jenkins.plugins.okidocki.DockerBuildWrapper$2.launch(DockerBuildWrapper.java:92)
            at hudson.Launcher$ProcStarter.start(Launcher.java:381)
            at hudson.Launcher$ProcStarter.join(Launcher.java:388)
            at jenkins.plugins.shiningpanda.command.Command.launch(Command.java:200)
            at jenkins.plugins.shiningpanda.utils.BuilderUtil.launch(BuilderUtil.java:232)
            at jenkins.plugins.shiningpanda.builders.PythonBuilder.perform(PythonBuilder.java:129)
            at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
            at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
            at hudson.model.Build$BuildExecution.build(Build.java:199)
            at hudson.model.Build$BuildExecution.doRun(Build.java:160)
            at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
            at hudson.model.Run.execute(Run.java:1759)
            at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
            at hudson.model.ResourceController.execute(ResourceController.java:89)
            at hudson.model.Executor.run(Executor.java:240)

I'm using jenkins v1.593 with oki-docki v1.1

**Comment by ndeloof** [comment]
I just tried to run "invoke top-level maven targets" using maven:3.3.3-jdk-8 as image to run the build into, and works for me with latest release.
