### ISSUE TITLE
Unable to use this plugin with docker remote API

### ISSUE THREAD

**Issue by denouche** [jenkinsci/docker-custom-build-environment-plugin#23]
Hi!

I would like to use this plugin in my full containerized environment.
My Jenkins is running in a container (so it does not have docker installed) and I would like to build my project using this plugin by using the docker remote API.

I explain: 
I am able in my job configuration to set the docker server URI (I tried both tcp:// and http://), but I'm not sure what it really does:
![dockerbuildenv](https://cloud.githubusercontent.com/assets/3081451/8349234/5ec130d8-1b1b-11e5-9aca-064203f7520d.png)

Because with this configuration my job execution fail with this error:
```
$ docker inspect 07f15b02106cce3b756eea19cba2c14ac2b149dc
FATAL: command execution failed
java.io.IOException: Cannot run program "docker": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at hudson.Proc$LocalProc.<init>(Proc.java:244)
	at hudson.Proc$LocalProc.<init>(Proc.java:216)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:803)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1136)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1101)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:325)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to defd831cfc1c@docker(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1360)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
	at hudson.remoting.Channel.call(Channel.java:753)
	at hudson.Launcher$RemoteLauncher.launch(Launcher.java:916)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at hudson.Launcher$ProcStarter.join(Launcher.java:388)
	at com.cloudbees.jenkins.plugins.docker_build_env.Docker.hasImage(Docker.java:61)
	at com.cloudbees.jenkins.plugins.docker_build_env.DockerfileImageSelector.prepareDockerImage(DockerfileImageSelector.java:42)
	at com.cloudbees.jenkins.plugins.docker_build_env.DockerDecoratedLauncher.launch(DockerDecoratedLauncher.java:48)
	at jenkins.plugins.nodejs.tools.DecoratedLauncher.launch(DecoratedLauncher.java:49)
	at jenkins.plugins.nodejs.tools.NpmPackagesBuildWrapper$2.launch(NpmPackagesBuildWrapper.java:88)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:97)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.Build$BuildExecution.build(Build.java:203)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	at hudson.Proc$LocalProc.<init>(Proc.java:244)
	at hudson.Proc$LocalProc.<init>(Proc.java:216)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:803)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1136)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1101)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:325)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

So I guess this parameter is not taken in consideration to use the Docker remote API instead of using Docker in command line.
Is it possible to use the Docker remote API with this plugin?

Moreover I already defined the Docker serveur URI as a "Docker cloud" in the global Jenkins configurations with this plugin: https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin so is it really necessary to define it again in my job configuration ?

Thanks in advance for your answer.

**Comment by ndeloof** [comment]
Your issue is not about local vs remote API usage, but the fact docker-custom-build-environment plugin do use docker cli to communicate with docker daemon, not a java-based client, so having docker executable available is a requirement.

**Comment by denouche** [comment]
Do you think it would be relevant to be able with this plugin to communicate with the docker daemon using another way that docker cli ? As you said for example using a java-based client ?

**Comment by ndeloof** [comment]
I'm indeed considering this. See https://github.com/jenkinsci/docker-custom-build-environment-plugin/tree/docker-java

**Comment by denouche** [comment]
Could be great!

**Comment by oleg-nenashev** [comment]
@ndeloof 
If you want to use docker-java, be aware about its shading due to the possible conflict with docker-plugin and docker-build-step. See issue referenced in https://github.com/jenkinsci/docker-traceability-plugin/pull/18 and https://github.com/jenkinsci/docker-traceability-plugin/pull/22 for a background

**Comment by ndeloof** [comment]
please also use issues.jenkins-ci.org to report issues on this plugin
